name: CI + CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: echo Hello, world!

  DeployDev:
    name: Deploy to Dev
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: Development
      url: 'http://dev.myapps.com'
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile
        run: echo Hello, world!
      - name: Deploy
        run: |
          echo I am deploying on dev!
          echo "$GITHUB_CONTEXT"
          echo "$(git rev-parse --short HEAD)"

  DeployStaging:
    name: Deploy to Staging
    needs: [DeployDev]
    runs-on: ubuntu-latest
    environment:
      name: Staging
      url: 'http://test.myapp.com'
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        run: |
          echo I am deploying on stage!
          echo "$GITHUB_CONTEXT"
          echo "$(git rev-parse --short HEAD)"

  DeployProd:
    name: Deploy to Production
    needs: [DeployStaging]
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: 'http://www.myapp.com'
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        run: |
          echo I am deploying on prod!
          echo "$GITHUB_CONTEXT"
          echo "$(git rev-parse --short HEAD)"